spring.application.name=k8s-demo-project
server.port=9000

## Data JPA and Postgres
spring.datasource.url=jdbc://postgresql://localhost:5432/k8s
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect